/configver                                        2
/panels                                           [1,2]
/panels/dark-mode                                 true
/panels/panel-1/icon-size                         24
/panels/panel-1/length                            100
/panels/panel-1/plugin-ids                        [23,2,3,25,6,8,9,10,11,12,13,24]
/panels/panel-1/position                          p=6;x=0;y=0
/panels/panel-1/position-locked                   true
/panels/panel-1/size                              26
/panels/panel-2/autohide-behavior                 1
/panels/panel-2/background-image                  file:///usr/share/branding-soplos/transparent-logo.png
/panels/panel-2/background-style                  0
/panels/panel-2/border-width                      0
/panels/panel-2/enable-struts                     true
/panels/panel-2/icon-size                         0
/panels/panel-2/length                            1,000000
/panels/panel-2/mode                              0
/panels/panel-2/nrows                             1
/panels/panel-2/plugin-ids                        [15,16,1,21,4]
/panels/panel-2/position                          p=10;x=0;y=0
/panels/panel-2/position-locked                   true
/panels/panel-2/size                              56
/plugins/plugin-1                                 docklike
/plugins/plugin-10                                notification-plugin
/plugins/plugin-11                                separator
/plugins/plugin-11/style                          0
/plugins/plugin-12                                clock
/plugins/plugin-12/digital-date-font              Sans 12
/plugins/plugin-12/digital-layout                 3
/plugins/plugin-12/digital-time-font              Sans 12
/plugins/plugin-13                                separator
/plugins/plugin-13/style                          0
/plugins/plugin-15                                showdesktop
/plugins/plugin-16                                separator
/plugins/plugin-2                                 tasklist
/plugins/plugin-21                                separator
/plugins/plugin-23                                whiskermenu
/plugins/plugin-23/button-icon                    /usr/share/branding-soplos/transparent-logo.png
/plugins/plugin-23/favorites                      [xfce4-web-browser.desktop,xfce4-mail-reader.desktop,xfce4-file-manager.desktop,xfce4-terminal-emulator.desktop]
/plugins/plugin-23/hover-switch-category          true
/plugins/plugin-23/position-categories-alternate  true
/plugins/plugin-23/position-commands-alternate    true
/plugins/plugin-23/position-search-alternate      true
/plugins/plugin-23/recent                         [soplos-theme-manager.desktop,calamares-install-soplos.desktop,gparted.desktop,yad-icon-browser.desktop,org.xfce.mousepad.desktop,org.xfce.mousepad-settings.desktop,xfce-keyboard-settings.desktop]
/plugins/plugin-24                                showdesktop
/plugins/plugin-25                                xfce4-clipman-plugin
/plugins/plugin-2/grouping                        1
/plugins/plugin-3                                 separator
/plugins/plugin-3/expand                          true
/plugins/plugin-3/style                           0
/plugins/plugin-4                                 thunar-tpa
/plugins/plugin-6                                 systray
/plugins/plugin-6/known-legacy-items              [miniaplicación gestor de la red,la conexión de red cableada «wired connection 1» está activa]
/plugins/plugin-6/square-icons                    true
/plugins/plugin-8                                 pulseaudio
/plugins/plugin-8/enable-keyboard-shortcuts       true
/plugins/plugin-8/show-notifications              true
/plugins/plugin-9                                 power-manager-plugin
