/backdrop/screen0/monitorVirtual-1/workspace0/last-image  /usr/share/backgrounds/xfce/004.jpg
/last/window-height                                       559
/last/window-width                                        775
