/configver                                        2
/panels                                           [1,2]
/panels/dark-mode                                 true
/panels/panel-1/icon-size                         24
/panels/panel-1/length                            100
/panels/panel-1/plugin-ids                        [23,1,3,4,25,2,6,8,10,11,12,13,24]
/panels/panel-1/position                          p=8;x=960;y=1066
/panels/panel-1/position-locked                   true
/panels/panel-1/size                              42
/panels/panel-2/autohide-behavior                 1
/panels/panel-2/length                            10,000000
/panels/panel-2/mode                              1
/panels/panel-2/plugin-ids                        [16]
/panels/panel-2/position                          p=1;x=1894;y=981
/panels/panel-2/position-locked                   true
/panels/panel-2/size                              50
/plugins/plugin-1                                 docklike
/plugins/plugin-10                                notification-plugin
/plugins/plugin-11                                separator
/plugins/plugin-11/style                          0
/plugins/plugin-12                                clock
/plugins/plugin-12/digital-date-font              Sans 12
/plugins/plugin-12/digital-layout                 3
/plugins/plugin-12/digital-time-font              Sans 12
/plugins/plugin-13                                separator
/plugins/plugin-13/style                          0
/plugins/plugin-16                                pager
/plugins/plugin-16/miniature-view                 true
/plugins/plugin-16/rows                           1
/plugins/plugin-16/wrap-workspaces                true
/plugins/plugin-2                                 screenshooter
/plugins/plugin-23                                whiskermenu
/plugins/plugin-23/button-icon                    /usr/share/branding-soplos/transparent-logo.png
/plugins/plugin-23/favorites                      [xfce4-web-browser.desktop,xfce4-mail-reader.desktop,xfce4-file-manager.desktop,xfce4-terminal-emulator.desktop]
/plugins/plugin-23/hover-switch-category          true
/plugins/plugin-23/position-categories-alternate  true
/plugins/plugin-23/position-commands-alternate    true
/plugins/plugin-23/position-search-alternate      true
/plugins/plugin-23/recent                         [soplos-theme-manager.desktop,soplos-welcome.desktop,xfce4-run.desktop,xfce-settings-manager.desktop,firefox-esr.desktop,gparted.desktop,yad-icon-browser.desktop,org.xfce.mousepad.desktop,org.xfce.mousepad-settings.desktop,xfce-keyboard-settings.desktop]
/plugins/plugin-24                                showdesktop
/plugins/plugin-25                                xfce4-clipman-plugin
/plugins/plugin-3                                 separator
/plugins/plugin-3/expand                          true
/plugins/plugin-3/style                           0
/plugins/plugin-4                                 xkb
/plugins/plugin-4/display-scale                   50
/plugins/plugin-4/display-type                    2
/plugins/plugin-4/group-policy                    0
/plugins/plugin-4/show-notifications              true
/plugins/plugin-6                                 systray
/plugins/plugin-6/known-legacy-items              [miniaplicación gestor de la red,la conexión de red cableada «wired connection 1» está activa]
/plugins/plugin-6/square-icons                    true
/plugins/plugin-8                                 pulseaudio
/plugins/plugin-8/enable-keyboard-shortcuts       true
/plugins/plugin-8/show-notifications              true
